const NAVIGATE_TO_REQUEST_PATIENT_INFO = 0;
const NAVIGATE_TO_REQUEST_APPOINTMENT_INFO = 1;
const NAVIGATE_TO_ALL_DONE_APPOINTMENT = 2;

// const PRIMARY_COLOR = '#CF212D';
// red color code
const PRIMARY_COLOR = '#B9212D';
// blue color code
// const PRIMARY_COLOR = '#0078D7';
const BLACK_COLOR = '#000000';
const WHITE_COLOR = '#ffffff';
